Multiple fixes: Implemented list sorting, Added AddProjectButton to Card
scaffold-eth/OP-RetroPGF3-Discovery-Voting pull request #119
Opened 2023-10-11 14:04 UTC by blahkheart

## Description

1. Fixed list sorting by creating ```ListsPageHeader``` component
2. Renamed ```ListHeader.tsx``` component to ```ProjectsPageHeader.tsx```
3. Refactored ```PageHeader``` component by creating ```AddProjectButton.tsx```
4. Added ```AddProjectsButton.tsx``` to projects Card
5. Modified project model to include ```projectLogoUrl```, and ```projectBannerUrl```
6. Implemented input focus when ```VoteModal``` is opened

## Additional Information

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #88 #93 #96 _

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address: dannithomx.eth

2023-10-11 14:27 UTC, ZakGriffith requested changes
Love the QOL updates and the card images here!  One thing I found is that when a project has a shorter description, the Add To Ballot button is not in the correct location when viewing on a wide screen.  It should be the to right side like the rest of them.

![image](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/assets/12072395/8525fb43-1f7e-4bcd-b018-2c42aee0f452)

2023-10-11 22:51 UTC, blahkheart commented
Noted, I'll get right to it.

2023-10-12 09:23 UTC, blahkheart commented
Fixed, please check and review

2023-10-12 14:00 UTC, ZakGriffith approved these changes

2023-10-12 14:00 UTC, merged